--- CREATE TABLE ----
-- Create Table Accounts -- 
CREATE TABLE ACCOUNT(
     user_id SERIAL PRIMARY KEY,
     username VARCHAR(50) UNIQUE NOT NULL,
     password VARCHAR(50) NOT NULL,
     email VARCHAR(250) UNIQUE NOT NULL,
     created_on TIMESTAMP NOT NULL,
     last_login TIMESTAMP
);

-- Create Table Job
CREATE TABLE JOB(
     JOB_ID SERIAL PRIMARY KEY,
     JOB_NAME VARCHAR(200) UNIQUE NOT NULL
);


-- Create account JobTable
CREATE TABLE account_JOB(
     USER_ID INTEGER REFERENCES account(user_id),
     JOB_ID INTEGER REFERENCES job(job_id),
     hire_date TIMESTAMP
);

--- INSERT ---
INSERT INTO account(username, password, email, created_on)
VALUES
('JONATHAN GOMES', 'LORDK1234', 'DARK@GMAIL.COM', LOCALTIMESTAMP);


INSERT INTO JOB(job_name)
VALUES
('AI&ML ENGINEER');

INSERT INTO JOB(job_name)
VALUES
('PRESIDENT');

INSERT INTO account_job(user_id, job_id, hire_date)
VALUES
(1,1,CURRENT_TIMESTAMP);

--- UPDATE ---
--SELECT * FROM account a ;

UPDATE account 
SET last_login = created_on ;

--SELECT * FROM account_job aj ;

-- UPDATE TABLE BASED ON OTHER TABLE
UPDATE account_job 
SET hire_date = a.created_on
FROM account a
WHERE a.user_id = account_job.user_id ; 

-- ALSO CAN VIEW CHANGES WITHOUT WRITING THE SELECT QUERY
UPDATE account 
SET last_login = CURRENT_TIMESTAMP
RETURNING email ,last_login , created_on;

-- DELETE --
INSERT INTO JOB(job_name)
VALUES
('GAMER');

DELETE FROM JOB
WHERE JOB.job_name IN ('GAMER', 'PRESIDENT')
RETURNING JOB.job_id , JOB.job_name ;

--- ALTER ---
CREATE TABLE INFO(
     INFO_ID SERIAL PRIMARY KEY,
     TITLE VARCHAR(200) NOT NULL,
     PERSON VARCHAR(50) NOT NULL UNIQUE
);
-- ALTER THE TABLE NAME (RENAME A TABLE NAME)
ALTER TABLE INFO
RENAME TO NEW_INFO;

ALTER TABLE new_info 
RENAME COLUMN  PERSON TO PERSON_NAME;

INSERT INTO new_info (title)
VALUES
('LONG VALUES RE BORING');

ALTER TABLE new_info 
ALTER COLUMN PERSON_NAME DROP NOT NULL;

SELECT * FROM new_info ni ;
--- DROP ----

SELECT * FROM new_info ni ;

ALTER TABLE new_info 
DROP COLUMN IF EXISTS PERSON_NAME;

--- CONSTRAINTS ----
CREATE TABLE EMPLOYEE(
     EMP_ID SERIAL PRIMARY KEY,
     FIRST_NAME VARCHAR(50) NOT NULL,
     LAST_NAME VARCHAR(50) NOT NULL,
     BIRTHDATE DATE CHECK (BIRTHDATE > '1900-01-01'),
     HIRE_DATE DATE CHECK (HIRE_DATE > BIRTHDATE) ,
     SALARY INTEGER CHECK (SALARY > 0)
);

--ALTER TABLE EMPLOYEEES RENAME TO EMPLOYEE;

INSERT INTO EMPLOYEE(FIRST_NAME, LAST_NAME, BIRTHDATE, HIRE_DATE, SALARY)
VALUES
('JOSE',
 'PORTILLA',
 '1900-11-03',
 '2010-01-01',
 100);
 
 INSERT INTO EMPLOYEE(FIRST_NAME, LAST_NAME, BIRTHDATE, HIRE_DATE, SALARY)
VALUES
('RAJ',
 'VARZEG',
 '2000-11-03',
 '2010-01-01',
 -100);
 
 SELECT * FROM EMPLOYEE;


