-- 1. Create the database
CREATE DATABASE School;

-- 2. Switch to the new database (for systems that support it)
-- \c School;  -- For PostgreSQL CLI
-- USE School; -- For MySQL or SQL Server

-- 3. Create the TEACHERS table
CREATE TABLE TEACHERS (
    TEACHER_ID SERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    HOMEROOM_NUMBER INTEGER,
    DEPARTMENT VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PHONE_NUMBER VARCHAR(100) UNIQUE NOT NULL
);

-- 4. Create the STUDENTS table
CREATE TABLE STUDENTS (
    STUDENT_ID SERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    HOMEROOM_NUMBER INTEGER,
    PHONE_NUMBER VARCHAR(100) NOT NULL UNIQUE,
    EMAIL VARCHAR(100) UNIQUE,
    GRADUATION_YEAR VARCHAR(4) NOT NULL
);
     
-- 5. Insert student Mark Watney (no email provided)
INSERT INTO STUDENTS (FIRST_NAME, LAST_NAME, PHONE_NUMBER, HOMEROOM_NUMBER, GRADUATION_YEAR)
VALUES ('Mark', 'Watney', '777-555-1234', 5, '2035');

-- 6. Insert teacher Jonas Salk
INSERT INTO TEACHERS (FIRST_NAME, LAST_NAME, HOMEROOM_NUMBER, DEPARTMENT, EMAIL, PHONE_NUMBER)
VALUES ('Jonas', 'Salk', 5, 'Biology', 'jsalk@school.org', '777-555-4321');



