------- VIEWS ------------
CREATE OR REPLACE VIEW CUSTOMER_INFO AS (
SELECT c.first_name, c.last_name, address, a.district FROM customer c 
JOIN address a ON
a.address_id = c.address_id
);

-- TO RUN THE VIEW
SELECT * FROM CUSTOMER_INFO;

-- TO DROP / DELETE THE VIEW
DROP VIEW IF EXISTS CUSTOMER_INFO;

-- RENAME VIEW
ALTER VIEW CUSTOMER_INFO RENAME TO CUST_INFO;

-- CALLING THE VIEW USING SELECT QUERY
SELECT * FROM CUST_INFO;